/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * An enumeration.
 */
export type JobType = 'clean' | 'chemscraper' | 'molli' | 'novostoic-optstoic' | 'novostoic-novostoic' | 'novostoic-enzrank' | 'novostoic-dgpredictor' | 'somn' | 'defaults';

export const JobType = {
    Clean: 'clean' as JobType,
    Chemscraper: 'chemscraper' as JobType,
    Molli: 'molli' as JobType,
    NovostoicOptstoic: 'novostoic-optstoic' as JobType,
    NovostoicNovostoic: 'novostoic-novostoic' as JobType,
    NovostoicEnzrank: 'novostoic-enzrank' as JobType,
    NovostoicDgpredictor: 'novostoic-dgpredictor' as JobType,
    Somn: 'somn' as JobType,
    Defaults: 'defaults' as JobType
};

