/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MoleculeWithAmount } from './moleculeWithAmount';


export interface NovostoicRequestBody { 
    jobId: string;
    user_email: string;
    primary_precursor: MoleculeWithAmount;
    target_molecule: MoleculeWithAmount;
    co_reactants: Array<MoleculeWithAmount>;
    co_products: Array<MoleculeWithAmount>;
    max_steps: number;
    max_pathways: number;
    is_thermodynamic_feasible: boolean;
    thermodynamical_feasible_reaction_only: boolean;
    use_enzyme_selection: boolean;
    num_enzyme_candidates: number;
}

