/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReactionSmiles } from './reactionSmiles';
import { ReactionKeggId } from './reactionKeggId';


export interface ReactionsInner { 
    type: string;
    smiles: string;
    molecule_number: string;
    molecule_inchi_or_smiles: string;
    reaction_keggid: string;
}

