/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SomnRequestBody { 
    jobId: string;
    user_email: string;
    reactant_pair_name: string;
    aryl_halide_name: string;
    aryl_halide_smiles: string;
    aryl_halide_reaction_site?: number;
    amine_name: string;
    amine_smiles: string;
    amine_reaction_site?: number;
}

