apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: somn-frontend
spec:
  ingressClassName: nginx
  rules:
  - host: somn.localhost
    http:
      paths:
      - backend:
          service:
            name: somn-frontend
            port:
              number: 80
        path: /
        pathType: ImplementationSpecific
---
# Enables the pods in a deployment to be accessible from outside the cluster
apiVersion: v1
kind: Service
metadata:
  name: somn-frontend
spec:
  selector:
    app: somn-frontend
  type: LoadBalancer
  ports:
    - protocol: "TCP"
      port: 80
---
# Defines the deployment of the app running in a pod on any worker node
apiVersion: apps/v1
kind: Deployment
metadata:
  name: somn-frontend
  labels:
    app: somn-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: somn-frontend
  template:
    metadata:
      labels:
        app: somn-frontend
    spec:
      containers:
        - name: somn-frontend
          image: moleculemaker/somn-frontend
          ports:
            - containerPort: 80
          imagePullPolicy: Always
